#!/bin/bash

subreddit=EarthPorn
limit=10

while [[ $1 ]]; do
    case $1 in
       -l) limit=$2; shift 2 ;;
       -r) subreddit=$2; shift 2 ;;
       *) echo "Unknown param: $1"; exit 1 ;;
    esac
done


curl -s -H "User-Agent: Foo" https://www.reddit.com/r/${subreddit}/hot.json?limit=$((limit + 3)) |
    jq -r '.data.children[] | select(.data.is_reddit_media_domain) | .data.url' |
    while read line; do
    fileName=${line##*/}
    if [[ -e $fileName ]]; then
	touch $fileName
    else
	curl -s -o $fileName $line
    fi
    ln -sf ../$fileName rotation/$((++i)).jpg

    (( i >= limit )) && break
done

